CREATE TABLE IF NOT EXISTS approval_outbox (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, event_id VARCHAR(64) NOT NULL UNIQUE,
 application_id BIGINT NOT NULL, event_type VARCHAR(64) NOT NULL, routing_key VARCHAR(128) NOT NULL,
 payload_json JSON NOT NULL, publish_status VARCHAR(16) NOT NULL DEFAULT 'PENDING', retry_count INT NOT NULL DEFAULT 0,
 next_retry_at DATETIME NULL, published_at DATETIME NULL, last_error VARCHAR(1000) NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS approval_message_consume_log (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, event_id VARCHAR(64) NOT NULL UNIQUE, application_id BIGINT NOT NULL,
 consume_status VARCHAR(16) NOT NULL, consumer_name VARCHAR(64) NOT NULL, retry_count INT NOT NULL DEFAULT 0,
 started_at DATETIME NULL, completed_at DATETIME NULL, last_error VARCHAR(1000) NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS approval_execution_lock (
 application_id BIGINT PRIMARY KEY, event_id VARCHAR(64) NOT NULL, locked_by VARCHAR(64) NOT NULL,
 locked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NOT NULL
);
