CREATE TABLE loan_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_no VARCHAR(64) NOT NULL,
    product_code VARCHAR(64), applicant_name VARCHAR(64), id_card_no VARCHAR(32), mobile VARCHAR(20),
    loan_amount DECIMAL(18,2), loan_term INT, employment_type VARCHAR(32), company_name VARCHAR(128),
    work_years INT, status VARCHAR(32), current_step VARCHAR(64), channel_code VARCHAR(32),
    created_at TIMESTAMP, updated_at TIMESTAMP
);

CREATE TABLE uploaded_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT, document_type VARCHAR(32),
    file_name VARCHAR(255), file_url VARCHAR(512), file_size BIGINT, file_hash VARCHAR(128),
    ocr_status VARCHAR(32), parse_result_json JSON, uploaded_at TIMESTAMP
);

CREATE TABLE fraud_risk_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT, risk_level VARCHAR(16),
    risk_score DECIMAL(10,2), risk_tags_json JSON, rule_hits_json JSON, suggested_action VARCHAR(32),
    created_at TIMESTAMP, updated_at TIMESTAMP
);

CREATE TABLE repayment_capacity_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT,
    stable_monthly_income DECIMAL(18,2), monthly_debt_payment DECIMAL(18,2), dti DECIMAL(10,4),
    foir DECIMAL(10,4), disposable_income DECIMAL(18,2), income_stability_score DECIMAL(10,2),
    max_affordable_emi DECIMAL(18,2), recommended_credit_limit DECIMAL(18,2),
    created_at TIMESTAMP, updated_at TIMESTAMP
);

CREATE TABLE approval_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT, decision_result VARCHAR(32),
    approved_amount DECIMAL(18,2), interest_rate DECIMAL(10,4), loan_term INT, reject_reason_code VARCHAR(64),
    decision_explanation CLOB, policy_references_json JSON, decided_by VARCHAR(64), decided_at TIMESTAMP,
    created_at TIMESTAMP, updated_at TIMESTAMP
);

CREATE TABLE manual_review_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT, ticket_no VARCHAR(64),
    review_status VARCHAR(32), assigned_to VARCHAR(64), trigger_reason VARCHAR(255), risk_summary CLOB,
    review_comment CLOB, reviewed_at TIMESTAMP, created_at TIMESTAMP, updated_at TIMESTAMP
);

CREATE TABLE approval_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT, report_type VARCHAR(32),
    report_url VARCHAR(512), report_version VARCHAR(32), generated_by VARCHAR(64), generated_at TIMESTAMP,
    created_at TIMESTAMP, updated_at TIMESTAMP
);

CREATE TABLE agent_task_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT, agent_name VARCHAR(64),
    task_name VARCHAR(128), input_summary CLOB, output_summary CLOB, status VARCHAR(32), duration_ms BIGINT,
    error_message CLOB, started_at TIMESTAMP, finished_at TIMESTAMP, created_at TIMESTAMP
);

CREATE TABLE tool_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT, agent_name VARCHAR(64),
    tool_name VARCHAR(128), request_payload JSON, response_payload JSON, call_status VARCHAR(32), retry_count INT,
    duration_ms BIGINT, error_message CLOB, called_at TIMESTAMP, created_at TIMESTAMP
);

CREATE TABLE llm_trace_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT, agent_name VARCHAR(64),
    model_name VARCHAR(64), prompt_summary CLOB, response_summary CLOB, input_tokens INT, output_tokens INT,
    duration_ms BIGINT, trace_status VARCHAR(32), created_at TIMESTAMP
);

CREATE TABLE policy_hit_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT, policy_id VARCHAR(64),
    clause_id VARCHAR(64), policy_title VARCHAR(255), clause_text CLOB, hit_source VARCHAR(64), created_at TIMESTAMP
);

CREATE TABLE state_transition_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT, from_status VARCHAR(32),
    to_status VARCHAR(32), trigger_event VARCHAR(64), operator_type VARCHAR(32), operator_name VARCHAR(64),
    remark VARCHAR(255), created_at TIMESTAMP
);
